package com.duka.app.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * V5 Entity additions — Product Management, Stock Intelligence, Notifications, Analytics.
 *
 * StockAdjustment: audit trail for all stock changes (sales, manual edits, restocks).
 * ProductAlert: smart alerts generated by StockIntelligenceWorker.
 * AppNotification: in-app notification centre for all roles.
 * Expense: manual expense entries for net profit calculation.
 */

@Entity(tableName = "stock_adjustments")
data class StockAdjustment(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val productId: Long,
    val businessId: Long,
    val delta: Int,                  // positive = stock added, negative = sold/removed
    val reason: String,              // "sale" | "voice_sale" | "client_sale" | "manual_edit" | "restock"
    val timestamp: Long = System.currentTimeMillis()
)

@Entity(tableName = "product_alerts")
data class ProductAlert(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val businessId: Long,
    val productId: Long,
    val type: String,        // "low_stock" | "slow_mover" | "restock_suggestion" | "top_seller"
    val message: String,
    val severity: String,    // "info" | "warning" | "critical"
    val isRead: Boolean = false,
    val createdAt: Long = System.currentTimeMillis()
)

@Entity(tableName = "app_notifications")
data class AppNotification(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val userId: Long,
    val businessId: Long,
    val type: String,         // "low_stock" | "slow_mover" | "restock" | "budget_warning" |
                              //  "budget_over" | "new_sale" | "chat_message" | "promo_live"
    val title: String,
    val body: String,
    val actionRoute: String,  // NavHost route to open when tapped
    val isRead: Boolean = false,
    val createdAt: Long = System.currentTimeMillis()
)

@Entity(tableName = "expenses")
data class Expense(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val businessId: Long,
    val label: String,
    val amount: Long,
    val periodStart: Long,
    val periodEnd: Long,
    val createdAt: Long = System.currentTimeMillis()
)
